<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions name="Logger" targetNamespace="urn:org.jmp:fsw-demo:0.0.1" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:tns="urn:org.jmp:fsw-demo:0.0.1" xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:mime="http://schemas.xmlsoap.org/wsdl/mime/" xmlns:http="http://schemas.xmlsoap.org/wsdl/http/">
  <wsdl:types>
<xsd:schema xmlns:xsd="http://www.w3.org/2001/XMLSchema" xmlns:tns="urn:org.jmp:fsw-demo:0.0.1" attributeFormDefault="unqualified" elementFormDefault="qualified" targetNamespace="urn:org.jmp:fsw-demo:0.0.1">
  <xsd:element name="string" nillable="true" type="xsd:string"/>
</xsd:schema>
  </wsdl:types>
  <wsdl:message name="logResponse">
    <wsdl:part name="return" element="tns:string">
    </wsdl:part>
  </wsdl:message>
  <wsdl:message name="log">
    <wsdl:part name="arg0" element="tns:string">
    </wsdl:part>
  </wsdl:message>
  <wsdl:portType name="LoggerPortType">
    <wsdl:operation name="log">
      <wsdl:input name="log" message="tns:log">
    </wsdl:input>
      <wsdl:output name="logResponse" message="tns:logResponse">
    </wsdl:output>
    </wsdl:operation>
  </wsdl:portType>
  <wsdl:binding name="LoggerSoapBinding" type="tns:LoggerPortType">
    <soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
    <wsdl:operation name="log">
      <soap:operation soapAction="log" style="document"/>
      <wsdl:input name="log">
        <soap:body use="literal"/>
      </wsdl:input>
      <wsdl:output name="logResponse">
        <soap:body use="literal"/>
      </wsdl:output>
    </wsdl:operation>
  </wsdl:binding>
  <wsdl:service name="Logger">
    <wsdl:port name="LoggerPort" binding="tns:LoggerSoapBinding">
            <http:address location="http://localhost:8080/fsw-demo/Logger"/>
        </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
