package com.example.switchyard.restproxy.services
import com.example.switchyard.restproxy.rest.model.UserIdentity

global java.util.Map globals

rule "AccessValid"
    when
        // insert conditional here
        username: UserIdentity(username == "userA")
    then
        // insert consequence here
        System.out.println("User is valid");
        username.setValid(true);
        globals.put("Result", username);
end

rule "AccessInvalid"
    when
        // insert conditional here
        username: UserIdentity(username != "userA")
    then
        // insert consequence here
        System.out.println("User is not valid");
        username.setValid(false);
        globals.put("Result", username);
end
